# Generated by Django 6.0.4 on 2026-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_color_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_ne',
            field=models.CharField(blank=True, help_text='Nepali name of the department (optional)', max_length=100),
        ),
    ]
