BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Login') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXX XX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
  X
  XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXX XXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXX X X
    XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXX XXXXXXXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX gettext(u'Sign in to Samparka') XXXXX
    
    XXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      BBBBB

      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Username or Email') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Password') XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Log In') XXXXXXXXX
    XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u"Don't have an account?")  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'Sign up') XXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB