BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Notifications') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXX X XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X

  XX XX XXXXXXXXXXXX XXXX XX XX
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX
    XXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XX XXXXXX XXX XX XXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXX
    XXXXXXXXX XXXXXXXXX
    XXXXX XXXX
    XXXX XXXXX
    XXXXXX XXXX
    XXXXXXX XXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX XXXX
    XXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XX
  X
  XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXX
    XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXX
  X
  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XX
    XXXXXXXX XX
    XXXXXXXXXXX XXXXXXX XXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXX XX
  X

  XX XXXXXX XXX XX
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXX XXXXXXX
    XXXX XX
    XXXXXXXX XX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXX XX XXXX XXXXXXX XXXXXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            BB BBBBBBBBBBBB B B
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            BB BBBBBBBBBBBBBBBBBBBB B B
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Messages') XXXXXXX
        XXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
          XXXX
        BBBBB
      XXXXXX

      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX
            X  gettext(u'+ File Incident') 
          XXXX
        XXXXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Log Out') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXX

  XXXX XXXXX XX XXXXXX XXXXXXXXXXXX XXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Notifications') XXXXX
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          FFFFFF  gettext(u'items recorded') 
        XXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBB BBBBB BB BBBBBBBBBBBBB
        BB BBBBBBBBBB
          XX XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBXXXXXXBBBBBXX
        BBBB
          XXXX XXXXXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBXXXXXXBBBBBXX
        BBBBB

          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXX XXXXXXXXXXXX XX XXXXXXXXXX XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BB BBB BBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New') XXXXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
            BB BBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
          XXXXXX

          BB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB

        BB BBBBBBBBBB
          XXXX
        BBBB
          XXXXXX
        BBBBB
      BBBBB
        XXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
             gettext(u'Your notification log is clear.') 
          XXXX
        XXXXXX
      BBBBBB
    XXXXXX
  XXXXXXX

  XXXX XXXXX XX XXXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Activity Control') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXX
           gettext(u'Stay continuously updated regarding updates to your filed reports, response feedback loops, and citizen authorization streams.') 
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB