BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Modify Account Profile') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX X XXXXX
  X
  XXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXX XX XXXX XXXXXXX XXXXXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXX

  XXXX XXXXX XX XXXXXX XXXXXXXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX gettext(u'Account Management Settings') XXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB

      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX X XXXX XXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      BBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Display Name') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX gettext(u'Email Address') XXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXX gettext(u'Profile Identity Avatar Picture') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
        BB BBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XX XXXXXXXX XXXX XXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX
           gettext(u'Save Adjustments') 
        XXXXXXXXX
      XXXXXX
    XXXXXXX
  XXXXXXX

  XXXX XXXXX XX XXXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXX
BBBBBBBB