BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Create Account') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XX XXXXXX XXXX XXXXXX XXXXXXXXXX XXXX XXXXX XXXXXX XX
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXX XX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
  X
  XXXXXXXXXXX X
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXX
    XXXXXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXX XXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXX X X
    XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXX XXXXXXXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX gettext(u'Join Samparka Today') XXXXX
    
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB

      BBB BBBBB BB BBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
          XXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXX XXX
          XXXXXX XXXXXXFFFFFFFFFFFFFFX 
                 XXXXXXX 
                 XXXXX 
                 XXXXXXXXXXXXXXXXXX 
                 BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
          
          BB BBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXX
              BBB BBBBB BB BBBBBBBBBBBBXXXXXXXXXBBBBBB
            XXXXX
          BBBBB
        XXXXXX
      BBBBBB

      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Create Account') XXXXXXXXX
    XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Already have an account?')  XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Log in') XXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB