BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
  BB BBBBBBB
     gettext(u'Edit Complaint') 
  BBBB
     gettext(u'Post a Complaint') SSSS S SSSSSSSSS
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXX X XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X
  XX XXXXX XXXXXXXXX XXX XXX XXXXXX XXXX XXXXXXX XXXXXX XXXX XXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX XXXXXX X
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XX XXXX XXXXXX XXXXXX XXXXXXXXXX XXX XX XXX XXXXXX XXXXX XX
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXXXXXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX BB BBB BBBBBBBXXXXXXBBBBBXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXX XXXX
        BB BBBBBBBXX  gettext(u'Edit Complaint') BBBBX  gettext(u'Post a Complaint') BBBBB
      XXXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX
         gettext(u'Help your community by reporting issues to the relevant departments.') 
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Title')  XXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXBBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Department')  XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
            
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXBBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Description')  XXXXXXXXX
          
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Describe the problem clearly. Include what, when, and severity.') XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXBBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Photos (optional)') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Attach photos of the issue (up to 5 images, 5MB each)') XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Location (optional)') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Click on the map to pin the exact location of the complaint.') XXXXXX
          
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX
          
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Location name (auto-filled when you click the map, or type manually)') XXXXXX
          XXXXXX
          
          XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
            
            
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX
          
          XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Post anonymously') XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'(your name will be hidden)') XXXXXXX
        XXXXXX

        BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXXXXXXXXX XXXXXX
          
        XXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXXXX
            BB BBBBBBB gettext(u'Save Changes') BBBB gettext(u'Submit Complaint') BBBBB
          XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Reporting Tips') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
           gettext(u'Clear headlines and exact pins make it much faster for local municipal units to dispatch repair contracts.') 
        XXXX
        XXX XXXXXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXX XX
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXX  gettext(u'Anonymity Notice') XXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXX
           gettext(u'Anonymized filings protect your profile info public-side, but corresponding administration teams will still see verification tokens to handle fraud.') 
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB