BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBB BBBBB X  gettext(u'Admin') BBBBBBBB

BBBBB BBBBBBBBBB

XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXX X XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X
  XX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX 
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX 
    XXXX XXXX 
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX 
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXX 
    XXXXXXXXXXX XXXXXXX 
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X
  XX XXXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX 
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX 
    XXXXXXXX XXX XXXXX 
    XXXXXXXXXXXXXX XXXX 
    XXXXXXXXXX XXXXXXXX 
    XXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XX XXXXX XXXXXXXX XXX XXXXXXX XXXXXXX XXXXX XXXXXXX XX
  XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
  X
XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
        
        
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXXXXX
XXXX

 XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
        XXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
XXXX
      XXXXXX
       BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Log Out') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    
    


    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
         
      XXXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXX X X XXXX gettext(u'Department administrative authorization system overview') XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Total') XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Pending') XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Verified') XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'In Progress') XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Solved') XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'All Assigned') XXXX
      XX XXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Pending') XXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Verified') XXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'In Progress') XXXX
      XX XXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Solved') XXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Rejected') XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBB BBBBBBBBB BB BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX

          XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
              FFFFFFFFFF
            XXXXXX
            
            XXXX XXXXXXXXXXXX XX XXXXXXXXXX XXXX
              XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX
                XX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              
              XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBXXXX gettext(u'Anonymous Citizen Report') XXXXXBBBBBBBBB
                XXXXXXXX FFFFFFFFFFF
                XXXXXXXX X FFFFFFFFF
                XXXXXXXX X FFFFFFFFF
                BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX X BBBBB
              XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX 
                 XXXXXXXXXXXXXXX 
                 XXXXXXXXXXXXXXXXXXXXXXXXX 
                 XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
                X  gettext(u'PDF Report') 
              XXXX
              XX XXXXXXX 
                 XXXXXXXXXXXXXXXXXXXXXXXXX 
                 XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                 gettext(u'View Details')  XXXXXX
              XXXX
            XXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXX XXXXX XXXXXXX XXXX
              BBBBBBBBBB

              XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Change Status') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXX     BB BBBBBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX gettext(u'Pending') XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXX    BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Verified') XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBX gettext(u'In Progress') XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXX      BB BBBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX gettext(u'Solved') XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXX    BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Rejected') XXXXXXXXX
                XXXXXXXXX
              XXXXXX

              XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXX XX XXXXXXXXXX XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Internal Dispatch Notes') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'e.g., Crew assigned to sector tracking operational deployment...') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX

              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXX gettext(u'Commit') XXXXXXXXX
            XXXXXXX

            XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXX XXXX XXXXXX
              
              BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXX XXXXXXXXXXXXX XXXXXXX
                  XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
                    X  ngettext(u'Show audit history (%(counter)s)', u'Show audit history (%(counter)s)', count) SSSS SSSSS SSSSSSS SSSSSSSSSSSSSPPPP PPPPP PPPPPPP PPPPPPPPPPPPP
                  XXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX X X X XXXXXXX
                    BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFXXXXXXX
                        XXXXXX
                        BB BBBBBBBB
                          XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX X X XX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX
                        BBBBB
                      XXXXXX
                    BBBBBB
                  XXXXXX
                XXXXXXXXXX
              BBBB
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'No internal system modification cycles logged.') XXXXXXXXXXX
              BBBBB

              BB BBBBBBBBBBBBBBBB BB BBBBBBBBBB
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXX
                  BBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Rejected by department allocation manager.') X XX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Completely drop validation for this incident filing record?') XXXXXX  gettext(u'Quick Reject') XXXXXXXXX
                XXXXXXX
              BBBBB
              
            XXXXXX
          XXXXXX

        XXXXXX
      BBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXX
            BB BBBBBBBBBBBBBBB gettext(u'No incident filings matching selected status allocation parameters.') BBBB gettext(u'No operational work order assignments recorded.') BBBBB
          XXXX
        XXXXXX
      BBBBBB
    XXXXXX

  XXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Administrative Rules') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXX
           gettext(u"Changing an assignment flag updates citizens immediately. Always append detailed descriptive notes when switching workflows to 'In Progress' or 'Solved' to ensure local transparency levels stay intact.") 
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB