BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBBBB
BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXX X XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X
  XXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXX XX
    XXXXXXXX XX
  X
  XXXXXXXXXXXXXX X
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXX XXXX
    XXXXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXX
  X
XXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX  gettext(u'Back to Feed') XXXX
    XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFF XXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXX X XXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXX

      BB BBBBBBBBBBBBBBBBBBBB
      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
    BBB BBB BB BBBBBBBBBBBBBBBBBBBB
      XXXXXXX XXXXXXXXXXXXXX XXXX
        XXXX XXXXXX XXXXX gettext(u'Verification reference') X
             XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XX
        BB BBBBBBBBBBB
          XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX X XXXXXX
            
          XXXXXXXXXXXXX
        BBBBB
      XXXXXXXXX
    BBBBBB
XXXXXX

      BBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX BB BBBBBBBBB BB BXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX BB BBBBBBBBB BB BBXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXX
     XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
         gettext(u'Discussion Stream') 
    XXXXXX

    BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB BB BBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX
           XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
            X  gettext(u'Message Department') 
        XXXX
    BBBBB
XXXXXX


      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBXX
            BBBBBBBBBB
            XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Write a comment...') X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Post') XXXXXXXXX
            XXXXXX
          XXXXXXX
        XXXXXX
      BBBBB
     

      BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXX 
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX FFFFFFFFF XXXXXXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      BBBBB
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
           gettext(u'No responses recorded yet. Start the coordination dialogue stream.') 
        XXXXXX
      BBBBBB
    XXXXXXXXXX
  XXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Assigned Jurisdiction') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFF FFFFFFFFFFFF FFFFFFFFXXXXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXXXX
XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXXXXXX
  XX XXXXX XXXXXXX XXXX XXX XXXXXX XXX XXXXXXX XXXXXX XXXXX XXXX XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXX X XXXXXXXXXXXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX XX XXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX XXXX XFFFFFFFFXXX
    X
  XXX
XXXXXXXXX
BBBBBBBB