BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Feed') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXX X XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X
  XX XXXX XXXXXX XXXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX XX
  XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
  X
  XX XXXXX XXXXXX XXXX XXXXXX XXXXXXX XXX XXXXXXXXX XXXX XXXXXX XXXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXX
    XXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXX
  X
XXXXXXXX



XXXXXXX
  XX XXXXXXXX XXXXXX XXXXXXXXXXXX XX

  XX XXXX XXX XXXX XXXX XXXXXXXX XXXXXX XXX XXXXX XXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XX XXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XX XXXX XX
  XXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXX
  X
XXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXX
    X
    XX XXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
    X
  XXX
XXXXXXXXX 



BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXX XX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
XXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXXXXX
XXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
XXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
XXXX
        
      XXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX
            X  gettext(u'+ File Incident') 
          XXXX
        XXXXXX
      BBBBB 

      
        BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Log Out') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      BBBBB


    XXXXXX
  XXXXXXXX

  XXXX XXXXX XX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXX XXXX XXXXXX XXXXXX XXXXXX XXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXX XXXXXXX XXXX
        XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Search citizen reports...') X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
        
        XXXX XXXXXX XXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
            BBBBBB
          XXXXXXXXX
        BBBBB

        BB BBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
            BBBBBB
          XXXXXXXXX
        BBBBB

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXX gettext(u'Filter') XXXXXXXXX
        BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Clear') XXXX
        BBBBB
      XXXXXXX
    XXXXXX

    XXXX XXXX XXXX XXXXXX XXXX XXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
      XXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXX XXXXXX XXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
              BB BBBBBBBBBBBXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXBBBBFFFFFFFFFFBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'File a new local municipal infrastructure report...') 
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Report') XXXXXXX
          XXXX
        XXXXXX
      BBBBB

      XXXX XXXX XXXXXXX XXXXXXX XXXX XXXXXXXX XXXXX XXX
      BBB BBBBBBBBB BB BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX
          
          XXXX XXX XXXXXXX XXX XXXX XXXX XXXXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXX XXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXBBBBFFFFFFFFFFBBBBB
              XXXX
            BBBBB

            XXXX XXXXXXXXXXXX XX XXXXXXXXXX XXXX
              XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBB gettext(u'Anonymous Citizen') BBBBBBBBB
                XXXXXXX
                BB BBBBBBBBBBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                     
                  XXXXXXX
                BBBBB
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
            XXXXXX
          XXXXXX

          XXXX XXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX X X XXX XX XXXXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
                X 
              XXXXXX
            BBBBB

            XXXX XXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXX
            BB BBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Verification reference') X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                BBBBBB
              XXXXXX
            BBBBB

            XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
              
              XXXX XXXXXX XXXXX XXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX gettext(u'Upvote') XX
                  X XXXXXX
                XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Downvote') XX
                  X XXXXXX
                XXXXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX  XXXXXX X XXXXXXX
              BBBBB
            XXXXXX

              XXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXX XXX
              XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX
                X 
              XXXX

              XXXX XXXXX XXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXX XXX
              XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXX
                X 
              XXXXXXX

              XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
                 gettext(u'View Thread') 
              XXXX
            XXXXXX

          XXXXXX
        XXXXXX
      BBBBB
        XXXX XXXXX XXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX X X XXX XXXX gettext(u'No matching operational citizen filings found.') XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Be the first to log an issue')  XXXXXXXXXX
        XXXXXX
      BBBBBB
    XXXXXX

    XXXX XXXX XXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXFFFFFFFFFFXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXFFFFFFFFFFXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Prev') XXXX
        BBBBB
        
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX X XXXXXX
           gettext(u'Page')   X 
        XXXXXXX

        BB BBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXFFFFFFFFFFXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXFFFFFFFFFFXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Next')  XXXXX
        BBBBB
      XXXXXX
    BBBBB

  XXXXXXX

  XXXX XXXXX XX XXXXX XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXX XXX
  

      XXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXX XXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Trending Threads') XXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
            XX XXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXX
                XXXXXXX XXXXXXX
                XXXXXXX XXXXXXX
              XXXXXX
            XXXX
          BBBBB
            XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXX gettext(u'No trending threads yet.') XXXX
          BBBBBB
        XXXXXX
      XXXXXXXXXX

     XXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Submission Protocols') XXXXX
  XXX XXXXXXXXXXXXXX XXX X X XX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
    XXXX gettext(u'Verify the issue falls within municipal jurisdiction.') XXXXX
    XXXX gettext(u'Attach clear, recent photos as evidence.') XXXXX
    XXXX gettext(u'Provide an accurate location for faster routing.') XXXXX
    XXXX gettext(u'Search existing reports first to avoid duplicate filings.') XXXXX
    XXXX gettext(u'Keep descriptions factual and free of abusive language.') XXXXX
  XXXXX
XXXXXXXXXX

      XXXX XXXXXX XXXXXXX XXXXXX XXXXXX XX XX XXXXXX XXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Follow Us') XXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXX X XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX X XXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXXXX

      XXXX XXXXXXX XXXX XXXXXXX XXXXX XXXXXX XXXXXX XXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
              BB BBBBBBBBBBBXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXBBBBFFFFFFFFFFBBBBB
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
          XXXX
        XXXXXXXXXX
      BBBBB

      XXXX XXXX XXXXXXXXXXX XXXXXX XXXXX XXX
      XXXXXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXX  gettext(u'Municipal Engagement Network Console System') XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Privacy Policy') XXXX
          XXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Terms of Service') XXXX
        XXXXXX
      XXXXXXXXX

    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB