BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'My Complaints') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXX XXXX XX XXXX XXXXXXX XXXXXXXXXX XXXXX XXX
 XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX

  XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
  XXXX

  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
      BB BBBBBBBBBBBB B B
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB
    XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXXXXX
  XXXX

  BB BBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXXXXXXBBBBBXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
    XXXX
  BBBBB

XXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX
            X  gettext(u'+ File Incident') 
          XXXX
        XXXXXX
      BBBBB 

      
        BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Log Out') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      BBBBB


    XXXXXX
  XXXXXXXX
  XXXX XXXX XX XXXXXX XXXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXX XXXXXX XXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXX
      XXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXX
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX gettext(u'Managing your recorded pipeline filings') XXXXXXX
      XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX gettext(u'+ New Complaint') XXXX
    XXXXXX

    XXXX XXXXXXX XXXXXXX XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX
      BBB BBBBBBBBB BB BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXX XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
          
        XXXXXXX
        BBBB
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXX XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
          X
        XXXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX
              
            XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFF F FF FFFFFFFFFFFXXXXXXX
            XXXXXXXX XXXXXXFFFFFFFFFFFXXXXXXX
            XXXXXXXX XXXXXXX XXXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXX XXX XXXXXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX
            
          XXXXXXX
          
          BB BBBBBBBBBBBBBBBB BB BBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX
            XX  gettext(u'Edit') 
          XXXX
          BBBBB
        XXXXXX

      XXXXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXX gettext(u"You haven't posted any complaints yet.") XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Post Your First Complaint') XXXX
      XXXXXX
      BBBBBB
    XXXXXX
  XXXXXXX

  XXXX XXXX XX XXXXX XXXXXXX XXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
      XXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Nepal Emblem') X XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX XX
          XXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'सम्पर्क — Samparka') XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Track Filing Suite') XXXXXX
          XXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX X X XXXX XXXX gettext(u'This private suite tracks pipeline logs submitted from your account. Upvoted items gain public visual traction on the feed stream rooms.') XXXX
        XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Filing Lifecycle') XXXXXX
        XXX XXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
          XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Editable by you until reviewed.') XXXXX
          XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Assigned to department ops.') XXXXX
          XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Marked complete with execution summary.') XXXXX
        XXXXX
      XXXXXX

    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB