BBBB BBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
    XXXXXXX
        XXXXX X
            XXXXX XX XXXXXXXXX
            XXXXXXX XXXX XXXX XXXX XXXXX
            XXXXXXXXXXXXX X
                XXXXXXXX XXXXX X XXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXX
                XXXXXXXXXX XXXX
                XXXXXX XXXXXXXX
            X
        X
        XXXX X
            XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXXX X
            XXXXXXXXXX XXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXX XXX XX
            XXXXXX XXXXXXXX
        X
        
        XX XXX XXXXXX XXXXXX XXXXX XXX XXXXXXXX XX
        XXXXXXXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXX XX X
            XXXXXXXX XXX XXXXX
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
            XXXXXX XXXX
            XXXXXXXXXX XXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXX XXXX
            XXXXXXXXXX XXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXX
        X
        
        XX XXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXXX XXXX
            XXXXXXX XXXX X XXXX XX
            XXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXXX X
            XXXXXXX XXX XXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Official Incident Filing Record') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX
             gettext(u'Filing Reference ID:')  X XXXXXXXX  gettext(u'Generated on:')  BBB BBBBBB BBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Core Details') XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Current Operational Status') XXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Assigned Department') XXXXX
            XXXXXXXXX
        XXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Filing Submitter') XXXXX
            XXXX
                BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXX gettext(u'Anonymous Citizen Report') XXXXXXXXX
                BBBB
                     XFFFFFFFFFFF FFFFFF FFFFF FFFFFFFX
                BBBBB
            XXXXX
        XXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Submission Date') XXXXX
            XXXXFFFFFFF FF F F FFFFXXXXX
        XXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX
            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Reported Location Target') XXXXX
            XXXXX XXXXX
        XXXXX
        BBBBB
    XXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Incident Description Statement') XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Internal System Modification Lifecycle & Audit History') XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
        BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXX  gettext(u'Status Transformed To:')  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXFFFFFFFFFFF FFFFXXXXXXX
                XXXXXX
                BB BBBBBBBB
                    XX XXXXXXXXXXXXXX XXX X X XX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX
                BBBB
                    XX XXXXXXXXXXXXXX XXX X X XX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'No dispatcher update context appended.') XXXX
                BBBBB
            XXXXXX
        BBBBBB
    BBBB
        XX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'No internal system modification cycles logged against this case profile.') XXXX
    BBBBB

XXXXXXX
XXXXXXX