BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB
BBBBB BBBBB gettext(u'Superadmin Dashboard') BBBBBBBB


BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXX XX XXXX XXXXXXX XXXXXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXX

  XXXX XXXXX XX XXXXXX XXXXXXXXX XXXXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXX

      XXXX XXXXXXXXX XXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXX XXXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX X X XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
             gettext(u'Superadmin Dashboard') 
          XXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
             gettext(u'All complaints across every department') 
          XXXX
        XXXXXX
      XXXXXX


      XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Total') XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Pending') XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX gettext(u'In Progress') XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Resolved') XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Rejected') XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXX XXXXXXXXXX XXX XXX
      XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXX BB BBB BBBBBBBBBBBBBXXXXXXXXXXXBBBBXXXXXXXXXBBBBB XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
           gettext(u'All') 
        XXXX
        BBB BBBB BB BBBBBBBBBBB
        XX XXXXXXXXXXXXX
           XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXBBBBXXXXXXXXXBBBBB XXXXXXX
           XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
        BBBBBB
      XXXXXX

      XXXX XXXXXXXXX XXXX XXXXX XXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        
        XXXX XXXXX XXXXXX XXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXX gettext(u'Complaint') XXXXXX
          XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXX gettext(u'Department') XXXXXX
          XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXX gettext(u'Posted by') XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX gettext(u'Status / Date') XXXXXX
        XXXXXX

        XXXX XXXX XXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXX
          BBB BBBBBBBBB BB BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX
            
            XXXX XXXXXXXXX XXXXXXX XXXXXXXX XXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX
                XX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                  
                XXXX
              XXXXXX
              BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
                X XXXXXX gettext(u'Message') XXXXXXX
              XXXX
              BBBBB
            XXXXXX

            XXXX XXXXXXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBB BBBBXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX

            XXXX XXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Anonymous') XXXXXXX
              BBBB
                
              BBBBB
            XXXXXX

            XXXX XXXXXX XXX XXX XXXX XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXX
                
              XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                FFFFFFF FF
              XXXXXXX
            XXXXXX

          XXXXXX
          BBBBB
          XXXX XXXXX XXXXX XXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXX XXXX gettext(u'No complaints found.') XXXX
          XXXXXX
          BBBBBB
        XXXXXX

      XXXXXX

    XXXXXX
  XXXXXXX

  XXXX XXXXX XX XXXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXX XXXXXXX XXXXXX XXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Quick Actions') XXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXX XXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX  gettext(u'Admin Panel') 
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X  gettext(u'Export CSV') 
          XXXX
        XXXXXX
      XXXXXXXXXX

      XXXX XXXXXXX XXXX XXXXXXX XXXXXX XXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
            BB BBBBBBBBBBBXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXBBBBFFFFFFFFFFBBBBB
          XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
        XXXX
      XXXXXXXXXX

    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB