BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB
BBBBB BBBBB gettext(u'Messages') BBBBBBBB

BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X
    XXXXXXXXX XXXXXX XXXXXXXXXXX
    XXXX X XXXXXXXXXXX
    XXXXXXXX XXXX XXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX XXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXX
  X
  XXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXX X

  XX XX XXXXXXXXXXXX XXXX XXXX XX XX
  XXXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXX XXXXX
    XXXXXXXXXXXX XXXXXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX X
  XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XXXXXXXX X

  XXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXX XXXX
    XXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXX XX
  X
  XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX X

  XXXXXXXXXXXX X XXXXX XX XXXXXXXXXX XX X
  XXXXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXX XXXXX X
  XXXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXX
  X
  XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXX
  X
  XXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X
  XXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX
    XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXX XXXX X

  XXXXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXX X XXXXXXXX XXXXX XXXX XXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX X
  XXXXXXXXXXX X
    XXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXX
  X
  XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXX X
XXXXXXXX
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXX
    XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
  XXX
XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXX XX XXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            BB BBBBBBBBBBBB B BXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
          XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Messages') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
        XXXX
      XXXXXX

      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX
            X  gettext(u'+ File Incident') 
          XXXX
        XXXXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Log Out') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXX

  XXXX XXXXX XX XXXXXXXXXXXX XXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXX
          X BB BBBBBBBB gettext(u'All Conversations') BBBB gettext(u'My Messages') BBBBB
        XXXXX
        BB BBBBBBBBBBBB B B
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'unread') XXXXXXX
        BBBBB
      XXXXXX
      BB BBB BBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXX  gettext(u'New Message') XXXX
      BBBBB
    XXXXXX

    BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'Search by user or subject...') X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXBB BBBBBBXXXBBBBBX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBXXXXXXBBBBBXX gettext(u'Open') XXXX
      XX XXXXXXXXXXXXXXXBB BBBBBBXXXBBBBBX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBB BB BBBXXXXXXBBBBBXX gettext(u'Closed') XXXX
    XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBB BBBB BB BBBBBBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBB B BXXXXXXBBBBBXX
        XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBXXXXXXBBBBBXX
          BB BBBBBBBBFFFFFFFFFFBBBBFFFFFFFFFFBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB
            XXXXXXX
            BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
                XXXXXXXX  
              XXXXXXX
            BBBBB
            BB BBBBBBBBBBB B BXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            BB BBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Closed') XXXXXXXBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX _("General Enquiry") XXXXXX
          BB BBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB gettext(u'You:')  BBBBB
          XXXXXX
          BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFXXXXXX
      XXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'No conversations yet.') XXXX
        BB BBB BBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXXXX gettext(u'Start a conversation') XXXX
        BBBBB
      XXXXXX
      BBBBBB
    XXXXXX
  XXXXXXX

  XXXX XXXXX XX XXXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Messaging') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXX
           gettext(u'Select a conversation to view the full thread and reply directly to the department handling your complaint.') 
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXXXX

XXXXXX
BBBBBBBB