BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBB gettext(u'New Message') BBBBBBBB
BBBBB BBBBBBBBBB
XXXXXXX
  XXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX X
  XXXXXXXXXXXX X
    XXXXXXXXXX XXXXXX
    XXXXXXX XXXX XXXXX
    XXXXXXXXXXX XXXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXX XXXXXXX
  X
  XXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX X
  XXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XX X
  XXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX X
  XXXXXXXXXXXX X XXXXXXXX XXXX XXXXX X
  XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXXX X X XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX X
  XXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX
  X
  XXXXXXXXXXXXX X
    XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXX X
    XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XX
  X
  XXXXXXXXXXXXX X XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX X
  XXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX X
  XXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXX X
  XXXXXXXXXXXXX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX X
  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXX XXXXXXX
  XXXXXXXXXXXXX XXXXXXXX X
    XXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXX
  X
  XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX
  X
  XXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXX X
  XXXXXXXXXXXXXXX X XXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX X
  XXXXXXXXXXXX X
    XXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX
    XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
  X
  XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXX X
  XXXXXXXXXXXXXX X
    XXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX
    XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXX
  X
  XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX X
XXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXX XX XXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Feed') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Messages') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX gettext(u'My Complaints') XXXXXXX
        XXXX
      XXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX
            X  gettext(u'+ File Incident') 
          XXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Log Out') X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXX
  XXXX XXXXX XX XXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'New Message') XXXXX
        XX XXXXXXXXXXXXXXXXXXX gettext(u'The relevant department admin will respond to your message as soon as possible.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXX XX XXXXXXXXX
             XXXXX XXXXX XX XXX XXX XX XXXXXXX XXXX XXXXX XXX XXXXXX XXX X
             XXXXXX XXXXXXXXXX XXXXX XX XXXXXXXXXX XXXXX XXXXXXXXX XXXXXXX
             XXXXX XXXX XX XXX XXXX XXXXXXX XXX
        BB BBBBBBBB
          BBB BBB BB BBBBBBBB
            BB BBBBBBBB BB BBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX 
              XXXXXX
            BBBBB
          BBBBBB
        BBBBB

        BB BBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          X  gettext(u'Regarding complaint:')  XX XXXXXXXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
        BBBBB

        XXXXX XXXXXXXXXXXXXX
          BBBBBBBBBB

          BB BBB BBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Department')  XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXXX XXXXXXXXX gettext(u'Select a department...') XXXXXXXXX
              BBB BBBB BB BBBBBBBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX XXXXXXXXX
              BBBBBB
            XXXXXXXXX
          XXXXXX
          BBBBB

          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Subject') XXXXXXXX
            
            BB BBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Message')  XXXXXXXXX
            
            BB BBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Send Message') XXXXXXXXX
          XXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX
  XXXX XXXXX XX XXXXX XXXXXXX XXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Messaging') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXX
           gettext(u"Messages about a specific complaint are automatically routed to that department's admin.") 
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXXXX
XXXXXX
BBBBBBBB