# Generated by Django 6.0.4 on 2026-04-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('department_admin', 'Department Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
