# Generated by Django 6.0.7 on 2026-07-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_due_date_complaint_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('solved', 'Solved'), ('withdrawn', 'Withdrawn'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
