XXXXXXXXX XXXXX
XXXXX XXXXXXXX

XXXXXX
  BBBB BBBBBB
  BBBB BBBB
  XXXXX XXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
  XXXXXXXBBBBB BBBBBXXXXXXXXBBBBBBBB X  gettext(u'Civic Complaint Platform') XXXXXXXX
  
  XXXX XXXX XXXXXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
  
  XXXX XXX XXXXXX XXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX

  XXXX XXXXXX XX XXXXXX XXXXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXX XX
  
  XXXXXXX
    XX XXXX XXXXXX XXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX XX
    XXXXXXXXXXXXXXXX X
      XXXXXXXXX XXXXXX XXXXXXXXXXX
      XXXX X XXXXXXXXXXX
      XXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    X
    XXXXXXXXXXXXXXX X
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXX X XXXXX
      XXXXXXXX X XXXXX
      XXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXX X
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
      XXXX XXXXX
    X
    XX XXXXXXXX XX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXX XX
    XXXXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXXXX XX
      XXXX XXXXXXXXX X XXXXX
      XXXXXXXXXXX XXXXXXXX
      XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
      XXXXXX XXXXXX
      XXXXXXXX XXXXX
      XXXXXXXX XXXXX
      XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXX XXX XX
      XXXXXXXXXXXXXXXXX XXX XXXXXX
      XXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXX XXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXX XX
      XXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXX XXXXX
      XXXXXXXXXXXXXXXX XXXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXX XXXX
      XXXXXXXXXXX XXXXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
    X
    XX XXXXXXX XXXXXX XXXXX XXXXXX XXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXX X
      XXXXXX XXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXX XXXX XXXX X XXXXX
      XXXXXXXX X XXXXX
      XXXXXXXXXXX XXXXXXXXXXX
    X
  XXXXXXXX
  BBBBB BBBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX

  XXXX XXXXXX XXXXXXXX XXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      
      XXXX XXXX XXXX XXXXX XXXXXX XXXXXX XXXXXXX XXX
      XXXX XXXX XXXX XXXXX XXXXXX XXXXXX XXXXXXX XXX
XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Nepal Emblem') X XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXXBBBBXXXXXXXXBBBBB
  XXXXXXX
XXXX
      XXXX XXXXX XXXX XXXXXXX XXXXX X XXXX XXXXXXXXXX XXXXXXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXX
        
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXXX

          BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXX XXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                  XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX XX
                BBBB
                  XXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXFFFFFFFFFFXXXXXXX
                BBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXX
              
              XXXX XXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'My Profile') XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Account Settings') XXXX
                BB BBBBBBBBBBBBB
                  XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'System Admin') XXXX
                BBBBB
                XXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXX XXX XX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX  gettext(u'Logout') XXXX
              XXXXXX
            XXXXXX
          BBBB
            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXX XXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX gettext(u'Login') XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX gettext(u'Sign Up') XXXX
          BBBBB
        XXXXXX

      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXX
  BB BBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBB BB BBBBBBBB
      XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXX X XXXXXXXXXXXXXXXX
      XXXXXX
    BBBBBB
  XXXXXX
  BBBBB

  XXXX XXXX XXXX XXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X X XXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    BBBBB BBBBBBBBBBBBBBB
  XXXXXXX

  XXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXX XX XXXXXXXXXXXX XXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX X XXXXX XXXXXXXX X XXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Nepal Emblem') X XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXX  gettext(u'Civic Operational Integrity Framework') XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Powered by citizens, for citizens.') XXXXXX
    XXXXXX
  XXXXXXXXX

XXXXXX

XXXX XXXX XXXXXXXXXXX XXXXXXX XXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX
BBBBB BBBBBBBBBBBBBBBB

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXX XXXXXXX
  
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXXXXXX XXXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
  X
  
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX X
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXX X XXXX X XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX X XXXXXXXXX
  XXXXXXXXXXXXXX
X
XXXXXXXXX
XXXXXXX
XXXXXXX